# Generated by Django 5.2.12 on 2026-03-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('JAZZ', 'Jazz'), ('POP', 'Pop'), ('ELECTRONIC', 'Electronic'), ('CLASSICAL', 'Classical'), ('ROCK', 'Rock'), ('HIPHOP', 'Hip Hop')], max_length=20)),
                ('mood', models.CharField(choices=[('CALM', 'Calm'), ('HAPPY', 'Happy'), ('ENERGETIC', 'Energetic'), ('ROMANTIC', 'Romantic'), ('SAD', 'Sad')], max_length=20)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('GRADUATION', 'Graduation'), ('HOLIDAY', 'Holiday'), ('CASUAL', 'Casual')], max_length=20)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('generation_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('singer_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.singermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='music.user')),
            ],
        ),
    ]
