# Generated by Django 5.2.5 on 2026-04-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_genre_mood_occasion_theme_alter_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
