# Generated by Django 5.2.5 on 2026-04-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_add_audio_url_to_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
