# Generated by Django 5.2.6 on 2026-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_add_external_id_to_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
